#pragma once
#define HZ_KEY_A              65
#define HZ_KEY_B              66
#define HZ_KEY_C              67
#define HZ_KEY_D              68
#define HZ_KEY_E              69
#define HZ_KEY_F              70
#define HZ_KEY_G              71
#define HZ_KEY_H              72
#define HZ_KEY_I              73
#define HZ_KEY_J              74
#define HZ_KEY_K              75
#define HZ_KEY_L              76
#define HZ_KEY_M              77
#define HZ_KEY_N              78
#define HZ_KEY_O              79
#define HZ_KEY_P              80
#define HZ_KEY_Q              81
#define HZ_KEY_R              82
#define HZ_KEY_S              83
#define HZ_KEY_T              84
#define HZ_KEY_U              85
#define HZ_KEY_V              86
#define HZ_KEY_W              87
#define HZ_KEY_X              88
#define HZ_KEY_Y              89
#define HZ_KEY_Z              90

#define HZ_KEY_0              48
#define HZ_KEY_1              49
#define HZ_KEY_2              50
#define HZ_KEY_3              51
#define HZ_KEY_4              52
#define HZ_KEY_5              53
#define HZ_KEY_6              54
#define HZ_KEY_7              55
#define HZ_KEY_8              56
#define HZ_KEY_9              57


#define HZ_KEY_ESCAPE         256
#define HZ_KEY_ENTER          257
#define HZ_KEY_TAB            258
#define HZ_KEY_BACKSPACE      259
#define HZ_KEY_INSERT         260
#define HZ_KEY_DELETE         261
#define HZ_KEY_RIGHT          262
#define HZ_KEY_LEFT           263
#define HZ_KEY_DOWN           264
#define HZ_KEY_UP             265
#define HZ_KEY_PAGE_UP        266
#define HZ_KEY_PAGE_DOWN      267
#define HZ_KEY_HOME           268
#define HZ_KEY_END            269
#define HZ_KEY_CAPS_LOCK      280
#define HZ_KEY_SCROLL_LOCK    281
#define HZ_KEY_NUM_LOCK       282
#define HZ_KEY_PRINT_SCREEN   283
#define HZ_KEY_PAUSE          284

#define HZ_KEY_F1             290
#define HZ_KEY_F2             291
#define HZ_KEY_F3             292
#define HZ_KEY_F4             293
#define HZ_KEY_F5             294
#define HZ_KEY_F6             295
#define HZ_KEY_F7             296
#define HZ_KEY_F8             297
#define HZ_KEY_F9             298
#define HZ_KEY_F10            299
#define HZ_KEY_F11            300
#define HZ_KEY_F12            301
#define HZ_KEY_F13            302
#define HZ_KEY_F14            303
#define HZ_KEY_F15            304
#define HZ_KEY_F16            305
#define HZ_KEY_F17            306
#define HZ_KEY_F18            307
#define HZ_KEY_F19            308
#define HZ_KEY_F20            309
#define HZ_KEY_F21            310
#define HZ_KEY_F22            311
#define HZ_KEY_F23            312
#define HZ_KEY_F24            313
#define HZ_KEY_F25            314
